### ISSUE TITLE
Testes tautológicos

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/hotel#3]
Checar se a função existe e se as chaves existem, logo ates de chamar a função e checar o valor das chaves... é meio redundante.

https://github.com/NicholasNeto/hotel/blob/master/test/hotel.js#L149-L155
https://github.com/NicholasNeto/hotel/blob/master/test/hotel.js#L180-L186

A não ser que essa função fizer parte de uma interface pública, não sei se precisa testar se elas existem, logo antes de testar se elas funcionam.

**Comment by NicholasNeto** [comment]
Estou de acordo, melhor manter teste que entregam mais valor. 
Refatorado no commit : fbf605158f0c4d1e8419b451a44400fe305ede6b

**Comment by thiagohersan** [comment]
ha. massa.
