### ISSUE TITLE
função findNumberDays() modifica o conteúdo de um input, sem avisar

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/hotel#4]
https://github.com/NicholasNeto/hotel/blob/master/hotel.js#L55

Essa linha muda o valor do objeto check_in. Ou seja, chamar a função duas vezes com as mesmas variáveis vai retornar valores diferentes porque na segunda vez que for chamada check_in vai ser igual a check_out.

Tem como usar uma variável temporária dentro da função para passar por todas as datas, sem modificar o objeto que foi passado pra função?

**Comment by NicholasNeto** [comment]
refatorando: usando uma variável temporaria, para manipular dados de data, afim de não ter dados errados ou entradas erradas numa possível rechamada da function 

5a5f6f0ef856405b407ab5d958556d1b0b264b12

**Comment by NicholasNeto** [comment]
Thiago , 

isso faz sentido ou não : eda2f13abd49935a209879e6761c99e9c57df9c7

Eu acredito que não , por que sempre que entrar nesta fucntion: findNumberDays esta linha de cdg       var tempEntrada = check_in;            var tempSaida = check_out;
vai recolocar os valores corrertos , mesmo que dentro das variaveis esteja com datas bem diferentes , ainda sim ele vai colocar a data correta novamente ..

**Comment by thiagohersan** [comment]
Não faz sentido zerar. São variáveis temporárias criadas dentro da função. Elas vão sumir automaticamente.

O que tá acontecendo é que essa linha não cria uma cópia do objeto, mas simplesmente dá um outro nome pra ele:
```var tempEntrada = check_in;```

Faz um print de ```tempEntrada``` (antes de zerar ela) e ```check_in``` no final da função. As duas mudam. ```check_in``` continua mudando.

**Comment by thiagohersan** [comment]
E acho que não precisa de uma cópia de ```check_out```. Ela só serve pra checar o final do ```while```.

**Comment by NicholasNeto** [comment]
impossível , a variavel check_in  continuar mudando , eu estou alterando a variavel  tempEntrada ..
esta será a primeira coisa que vou ver amanhã , 

sobre a check_out , estou plenamente de acordo ..vou refatorar tbm

**Comment by thiagohersan** [comment]
Do jeito que está, ```tempEntrada``` é só outro nome para o mesmo objeto. Mudando um, muda o outro.

Testa esse código no console do chrome:
```
var check_in = new Date(2018, 0, 1);
var tempEntrada = check_in;

console.log("check_in [antes]: "+check_in);
console.log("tempEntrada [antes]: "+tempEntrada);

tempEntrada.setDate(tempEntrada.getDate() + 1);

console.log("tempEntrada [depois]: "+tempEntrada);
console.log("check_in [depois]: "+check_in);
 ```

**Comment by thiagohersan** [comment]
Você tem que criar um ***novo*** objeto com o mesmo valor do objeto original.

**Comment by NicholasNeto** [comment]
EU entendi que isso acontece por que o objeto  temporario ele era uma referencia para o objeto original. 
ou seja , alterando a copia, voce alterava os parâmetros  do variável antiga. 

EU entendi que isso é uma característica da linguagem, e tenho que aceitar que é assim e pronto ..
Mas agora fiquei com a duvida , será que tem alguma linguagem quem não traz esta " limitação " 

chamo de limitação , por que pra mim é , imagina os riscos que são de voce ter uma variavel  que altera o comportamento ou parâmetros de outra variável que pode estar sendo utilizada em outro lugar ... 

para mim  isso a torna uma limitação da  linguagem e pior isso acontece não só com objetos , eu fui testar e isso acontece com listas tbm !!!!!

enfim eu vou tentar , buscar agora linguagem que não tem este tipo de comportamento com os objetos e as listas
