### ISSUE TITLE
Possível erro de lógica no cálculo de dias

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/hotel#6]
Eu estava vendo os testes e pensando um pouco sobre essa linha:
https://github.com/NicholasNeto/hotel/blob/master/hotel.js#L48

Quando a gente fica num hotel, o que é cobrado é o numero de noites que a gente dorme lá.
Então, se eu fico entre os dias 11 e 14, só serão cobradas 3 diárias (e não 4). Entre os dias 10 e 12 são 2 diárias.

**Comment by NicholasNeto** [comment]
SIM , voce tinha ração...
Foi resolvido este problema desta forma : 

mudei a logica do while,   anteriormente ele percorria o laço  enquanto era <= 
mas agora ele percorre o laço enquanto o numero de dias for menor ao de saida .. 

(entrada < saida) 
{
faça
}

**Comment by thiagohersan** [comment]
exato. show de bola.
